# git_ops-K8-config/overlays/local/patches/app1-service-patch.yaml
apiVersion: v1
kind: Service
metadata:
  name: insurance-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
