apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gloziksoft/git_ops-K8-config/settings/keys
    targetRevision: HEAD
    path: overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: booking-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
