apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-insurance-app
  labels:
    app: mariadb
    tier: database

spec:
  serviceName: mariadb-service
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb
        tier: database

    spec:
      # 🔽 ConfigMap s init.sql
      volumes:
        - name: mariadb-init
          configMap:
            name: mariadb-init-sql

      containers:
      - name: mariadb-container
        image: mariadb:10.11
        ports:
          - containerPort: 3306
            name: mariadb

        volumeMounts:
          # 📦 databázové dáta
          - name: mariadb-volume
            mountPath: /var/lib/mysql

          # 📥 SQL záloha – spustí sa IBA pri prvom štarte
          - name: mariadb-init
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true

        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password

          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-user

          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-password

          - name: MARIADB_DATABASE
            value: insurance_db

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

  volumeClaimTemplates:
    - metadata:
        name: mariadb-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi
