apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-insurance-app
  labels:
    app: mariadb
    tier: database

spec:
  serviceName: mariadb-service
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb
        tier: database

    spec:
      containers:
        - name: mariadb-container
          # ✅ TVOJ DB IMAGE S init.sql
          image: ghcr.io/gloziksoft/insurance-db:prod

          ports:
            - containerPort: 3306
              name: mariadb

          volumeMounts:
            # 📦 PERSISTENTNÉ DÁTA
            - name: mariadb-volume
              mountPath: /var/lib/mysql

          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-root-password

            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password

            - name: MARIADB_DATABASE
              value: insurance_db

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

  volumeClaimTemplates:
    - metadata:
        name: mariadb-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi
